name: Backend CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # Optional: You can add tests later
      - name: Run build (skip if not required)
        run: echo "No build step for backend"

      - name: Docker build
        run: docker build -t passgo-backend .
    