name: Backend CI/CD

on:
  push:
    branches: [main]

  workflow_dispatch:  # <--- same level as 'push'

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:${{ github.sha }} .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:latest
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:latest
            sudo docker stop passgo-backend || true
            sudo docker rm passgo-backend || true
            sudo docker run -d --name passgo-backend -p 5000:5000 \
              -e MONGO_URI=${{ secrets.MONGO_URI }} \
              -e PORT=${{ secrets.PORT }} \
              -e PASSGO_MAIL=${{ secrets.PASSGO_MAIL }} \
              -e PASSGO_MAIL_PASSWORD=${{ secrets.PASSGO_MAIL_PASSWORD }} \
              -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
              -e REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} \
              -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e RAZORPAY_KEY_ID=${{ secrets.RAZORPAY_KEY_ID }} \
              -e RAZORPAY_KEY_SECRET=${{ secrets.RAZORPAY_KEY_SECRET }} \
              -e REDIS_URL=${{ secrets.REDIS_URL }} \
              -e REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} \
              -e REDIS_TOKEN=${{ secrets.REDIS_TOKEN }} \
              -e OCR_SPACE_API_KEY=${{ secrets.OCR_SPACE_API_KEY }} \
              -e CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} \
              -e CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} \
              -e CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} \
              -e SUPER_ADMIN_ID=${{ secrets.SUPER_ADMIN_ID }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/passgo-backend:latest
